version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mkr_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    network_mode: host
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mkr_frontend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped